/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PageDetail {
        "item": string;
        "productDescription": string;
        "productId": string;
        "productImage": string;
        "productName": string;
        "productPrice": string;
        "productPromo": string;
    }
    interface PageHome {
        "products": Array<any>;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageDetailElement extends Components.PageDetail, HTMLStencilElement {
    }
    var HTMLPageDetailElement: {
        prototype: HTMLPageDetailElement;
        new (): HTMLPageDetailElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-detail": HTMLPageDetailElement;
        "page-home": HTMLPageHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageDetail {
        "item"?: string;
        "productDescription"?: string;
        "productId"?: string;
        "productImage"?: string;
        "productName"?: string;
        "productPrice"?: string;
        "productPromo"?: string;
    }
    interface PageHome {
        "products"?: Array<any>;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-detail": PageDetail;
        "page-home": PageHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-detail": LocalJSX.PageDetail & JSXBase.HTMLAttributes<HTMLPageDetailElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
        }
    }
}
